version: '3.7'

services:

  elasticsearch1:
    image: elasticsearch:8.2.3
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m -Des.index.number_of_replicas=0 -Des.enforce.bootstrap.checks=true
      xpack.security.enabled: 'false'
      xpack.ml.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
      cluster.initial_master_nodes: elasticsearch1,elasticsearch2,elasticsearch3
      discovery.seed_hosts: elasticsearch2,elasticsearch3
      node.name: elasticsearch1
      cluster.name: es-cluster
      bootstrap.memory_lock: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 30

  elasticsearch2:
    image: elasticsearch:8.2.3
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m -Des.index.number_of_replicas=0 -Des.enforce.bootstrap.checks=true
      xpack.security.enabled: 'false'
      xpack.ml.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
      cluster.initial_master_nodes: elasticsearch1,elasticsearch2,elasticsearch3
      discovery.seed_hosts: elasticsearch2,elasticsearch3
      node.name: elasticsearch2
      cluster.name: es-cluster
      bootstrap.memory_lock: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 30

  elasticsearch3:
    image: elasticsearch:8.2.3
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m -Des.index.number_of_replicas=0 -Des.enforce.bootstrap.checks=true
      xpack.security.enabled: 'false'
      xpack.ml.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
      cluster.initial_master_nodes: elasticsearch1,elasticsearch2,elasticsearch3
      discovery.seed_hosts: elasticsearch2,elasticsearch3
      node.name: elasticsearch3
      cluster.name: es-cluster
      bootstrap.memory_lock: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 30

  logstash:
    image: logstash:8.2.3
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.2.3
    environment:
<<<<<<< HEAD
      server.name: localhost
=======
      SERVER_NAME: localhost
>>>>>>> 1788c1c93cbc35eb41e081fb2fae2914925a5001
      ELASTICSEARCH_HOSTS: "http://elasticsearch1:9200","http://elasticsearch2:9200","http://elasticsearch3:9200"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch